sudo: required
dist: trusty

services:
  - docker

before_install:
  - curl -fsSL https://raw.githubusercontent.com/excars/excars-back/master/Pipfile > Pipfile
  - curl -fsSL https://raw.githubusercontent.com/excars/excars-back/master/Pipfile.lock > Pipfile.lock

script:
  - docker build . -t excars/excars-base

after_success:
  - rm -rf Pipfile Pipfile.lock

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master